import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavBar from "./components/NavBar";
import ContextWrapper from "./components/ContextWrapper";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {


  return (
    <html lang="en">
      <ContextWrapper >

        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased bg-slate-100`}
        >
          <NavBar />
          <div className="h-screen px-40 pt-20">
            {children}
          </div>
        </body>
      </ContextWrapper>
    </html>
  );
}
